import pandas as pd
import os

# ================================================
# 0. SETUP: CREATING A "MESSY" CSV FILE
# ================================================
# We create a file that mimics real-world dirty data:
# - Lines 1-2: Junk text (Metadata/Logs)
# - Line 3: Actual Header
# - Line 4-6: Data
# - It also has a specific ID column we want to use as an Index.

csv_content = """(Report Generated by System X)
(Confidential Data - Internal Use Only)
OrderID,Product,Price,Region,SalesPerson
101,Laptop,1000,US,Alice
102,Mouse,25,UK,Bob
103,Monitor,300,US,Charlie
"""

filename = 'messy_sales_data.csv'
with open(filename, 'w') as f:
    f.write(csv_content)

print(f"Created '{filename}' for testing.\n")


# ================================================
# 1. PANDAS READ_CSV VARIATIONS
# ================================================

# ------------------------------------------------
# 1.1 The Problem: Loading it "Normally"
# ------------------------------------------------
# If we just read it, Pandas gets confused by the top junk lines.

# print("--- 1. Bad Load (Default) ---")

# bad_df = pd.read_csv(filename)
# print(bad_df.head())
# Result: It tries to make '(Report Generated...)' the column name!


# ------------------------------------------------
# 1.2 skiprows - Handling Junk at the Top
# ------------------------------------------------
# We know the first 2 lines are garbage. We skip them.
# The 3rd line (Index 2) becomes the header.

print("\n--- 2. Using 'skiprows=2' ---")
df = pd.read_csv(filename, skiprows=2)
print(df)
# Result: Columns are correctly identified as OrderID, Product, etc.


# ------------------------------------------------
# 1.3 index_col - Setting the ID immediately
# ------------------------------------------------
# Instead of 0, 1, 2... we want 'OrderID' to be the row label.
# You can pass the column NAME or the column INDEX (0).

print("\n--- 3. Using 'index_col' ---")
df_indexed = pd.read_csv(filename, skiprows=2, index_col='OrderID')
print(df_indexed)
# Result: OrderID is now the Index.


# ------------------------------------------------
# 1.4 usecols - Loading only what you need
# ------------------------------------------------
# Imagine the file has 100 columns, but you only want Product and Price.
# This saves MASSIVE amounts of memory on large files.

print("\n--- 4. Using 'usecols' ---")
df_subset = pd.read_csv(filename, skiprows=2, usecols=['Product', 'Price'])
print(df_subset)
# Result: Only 2 columns loaded.


# ------------------------------------------------
# 1.5 header=None & names=... (No Headers in File)
# ------------------------------------------------
# sometimes a file has NO header row at all.
# Let's make a quick temporary file with NO headers.
no_header_content = "Laptop,1000\nMouse,25"
with open('no_header.csv', 'w') as f:
    f.write(no_header_content)

print("\n--- 5. Handling Files with NO Header ---")

# Option A: header=None (Auto-generates 0, 1, 2...)
df_none = pd.read_csv('no_header.csv', header=None)
print("Option A (Auto numbers):\n", df_none)

# Option B: names=[...] (Manually naming them)
df_named = pd.read_csv('no_header.csv', header=None, names=['Item', 'Cost'])
print("Option B (Manual names):\n", df_named)


# ------------------------------------------------
# 1.6 nrows - Previewing Huge Files
# ------------------------------------------------
# If a file is 10GB, you don't want to load it all just to peek.
# Load only the first N rows.

print("\n--- 6. Using 'nrows=2' ---")
df_small = pd.read_csv(filename, skiprows=2, nrows=2)
print(df_small)
# Result: Only loads the first 2 data rows.

# Cleanup
# os.remove(filename)
# os.remove('no_header.csv')